In [3]:

from pathlib import Path
import pandas as pd

# Execute o notebook a partir da pasta notebooks/
RAW = Path("../data/raw")

arquivos = []

for caminho in RAW.rglob("*"):
    if caminho.is_file():
        arquivos.append({
            "arquivo": caminho.name,
            "pasta": str(caminho.parent.relative_to(RAW)),
            "extensao": caminho.suffix.lower(),
            "tamanho_mb": round(caminho.stat().st_size / 1024**2, 2)
        })

inventario = pd.DataFrame(arquivos)

display(inventario)

,arquivo,pasta,extensao,tamanho_mb
0,sismigra_2024.csv,migracao,.csv,55.28
1,sismigra_ativos.csv,migracao,.csv,365.85
2,sismigra_janeiro_agosto_2026.csv,migracao,.csv,36.61
3,sismigra_janeiro_dezembro_2025.csv,migracao,.csv,58.40
4,RAIS_CTPS_CAGED_2025_MOV.csv,trabalho,.csv,107.12
5,RAIS_CTPS_CAGED_2026_MOV.csv,trabalho,.csv,76.08
6,RAIS_CTPS_ESTOQUE_2025.csv,trabalho,.csv,49.38
7,Tabela_Curso_Tecnico_2025_V2.csv,educacao\Censo Escolar 2025,.csv,7.84
8,Tabela_Docente_2025_V2.csv,educacao\Censo Escolar 2025,.csv,84.25
9,Tabela_Escola_2025_V2.csv,educacao\Censo Escolar 2025,.csv,134.87
10,Tabela_Gestor_Escolar_2025_v2.csv,educacao\Censo Escolar 2025,.csv,50.03
11,Tabela_Matricula_2025_V2.csv,educacao\Censo Escolar 2025,.csv,117.61
12,Tabela_Turma_2025_V2.csv,educacao\Censo Escolar 2025,.csv,95.29
13,MICRODADOS_CADASTRO_CURSOS_2024.CSV,educacao\INEP Ensino Superior,.csv,431.87
14,MICRODADOS_ED_SUP_IES_2024.CSV,educacao\INEP Ensino Superior,.csv,0.95

In [4]:
#preparando o inventário

from pathlib import Path
import pandas as pd

#Caminho para a pasta de dados
RAW = Path("../data/raw")

# Verificar se a pasta foi encontrada
print(f"Pasta RAW encontrada: {RAW.exists()}")

Pasta RAW encontrada: True

In [5]:
# Listar todos os arquivos CSV
arquivos = list(RAW.rglob("*.csv"))
print(f"Arquivos CSV encontrados: {len(arquivos)}")

for arquivo in arquivos:
    print(f"Arquivo: {arquivo.name}, Tamanho: {round(arquivo.stat().st_size / 1024**2, 2)} MB")

Arquivos CSV encontrados: 15
Arquivo: sismigra_2024.csv, Tamanho: 55.28 MB
Arquivo: sismigra_ativos.csv, Tamanho: 365.85 MB
Arquivo: sismigra_janeiro_agosto_2026.csv, Tamanho: 36.61 MB
Arquivo: sismigra_janeiro_dezembro_2025.csv, Tamanho: 58.4 MB
Arquivo: RAIS_CTPS_CAGED_2025_MOV.csv, Tamanho: 107.12 MB
Arquivo: RAIS_CTPS_CAGED_2026_MOV.csv, Tamanho: 76.08 MB
Arquivo: RAIS_CTPS_ESTOQUE_2025.csv, Tamanho: 49.38 MB
Arquivo: Tabela_Curso_Tecnico_2025_V2.csv, Tamanho: 7.84 MB
Arquivo: Tabela_Docente_2025_V2.csv, Tamanho: 84.25 MB
Arquivo: Tabela_Escola_2025_V2.csv, Tamanho: 134.87 MB
Arquivo: Tabela_Gestor_Escolar_2025_v2.csv, Tamanho: 50.03 MB
Arquivo: Tabela_Matricula_2025_V2.csv, Tamanho: 117.61 MB
Arquivo: Tabela_Turma_2025_V2.csv, Tamanho: 95.29 MB
Arquivo: MICRODADOS_CADASTRO_CURSOS_2024.CSV, Tamanho: 431.87 MB
Arquivo: MICRODADOS_ED_SUP_IES_2024.CSV, Tamanho: 0.95 MB

In [ ]:
# Inspecionando o arquivo sismigra_janeiro_dezembro_2025.csv

arquivo = RAW / "migracao" / "sismigra_janeiro_dezembro_2025.csv"

df = pd.read_csv(
    arquivo, 
    sep=";",
    encoding="utf-8",
    nrows = 5
)

display(df)

,DATAREGISTRO,AMPARO,AMPARO_DESCRICAO,CLASSIFICACAO_REGISTRO,DATAENTRADA,UNIDADE_FED_RESIDENCIA,MUNICIPIO_RESIDENCIA,PAIS_NASCIMENTO,PAIS_NACIONALIDADE,CONTINENTE,FAIXA_ETARIA,SEXO,ESTADO_CIVIL,PROFISSAO,STATUS,CLASSIFICACAO_REVISADA,TIPOLOGIA_AMPAROS
0,2025,233,233 - FRONTEIRICO - ARGENTINO D 8636/2016,Fronteiriço,2023,PR,FOZ DO IGUAÇU,ARGENTINA,ARGENTINA,AMÉRICA DO SUL,40 |-- 65 anos,Masculino,CASADO,"EMPREGADO DE ESCRITORIO, SECRETARIO, BANCARIO ...",Ativo,FRONTEIRIÇO,FRONTEIRIÇOS
1,2025,233,233 - FRONTEIRICO - ARGENTINO D 8636/2016,Fronteiriço,2024,PR,FOZ DO IGUAÇU,ARGENTINA,ARGENTINA,AMÉRICA DO SUL,65 |-- anos,Masculino,DESCONHECIDO,OUTRA OCUPACAO NAO CLASSIFICADA,Ativo,FRONTEIRIÇO,FRONTEIRIÇOS
2,2025,233,233 - FRONTEIRICO - ARGENTINO D 8636/2016,Fronteiriço,2024,-,NÃO ESPECIFICADO,ARGENTINA,ARGENTINA,AMÉRICA DO SUL,15 |-- 25 anos,Feminino,SOLTEIRO,ESTUDANTE,Ativo,FRONTEIRIÇO,FRONTEIRIÇOS
3,2025,233,233 - FRONTEIRICO - ARGENTINO D 8636/2016,Fronteiriço,2024,-,NÃO ESPECIFICADO,ARGENTINA,ARGENTINA,AMÉRICA DO SUL,15 |-- 25 anos,Masculino,DESCONHECIDO,OUTRA OCUPACAO NAO CLASSIFICADA,Ativo,FRONTEIRIÇO,FRONTEIRIÇOS
4,2025,190,190 - FRONTEIRICO - BOLIVIA - DECRETO 6737/09,Fronteiriço,2025,MS,CORUMBÁ,BOLÍVIA,BOLÍVIA,AMÉRICA DO SUL,40 |-- 65 anos,Masculino,SOLTEIRO,"MOTORISTA, CONDUTOR, OU OUTRO TRABALHADOR, DE ...",Ativo,FRONTEIRIÇO,FRONTEIRIÇOS

In [ ]:
# Vendo os nomes das colunas do arquivo sismigra_janeiro_dezembro_2025.csv

print("Número de colunas:", len(df.columns))

for coluna in df.columns:
    print(coluna)

Número de colunas: 17
DATAREGISTRO
AMPARO
AMPARO_DESCRICAO
CLASSIFICACAO_REGISTRO
DATAENTRADA
UNIDADE_FED_RESIDENCIA
MUNICIPIO_RESIDENCIA
PAIS_NASCIMENTO
PAIS_NACIONALIDADE
CONTINENTE
FAIXA_ETARIA
SEXO
ESTADO_CIVIL
PROFISSAO
STATUS
CLASSIFICACAO_REVISADA
TIPOLOGIA_AMPAROS

In [35]:
# Repetindo a inspeção em todos os arquivos CSV encontrados


resultado = []

for arquivo in arquivos:

    try:
        df = pd.read_csv(
            arquivo,
            sep=";",
            encoding="utf-8",
            nrows=5
        )
        codificacao = "utf-8"

    except UnicodeDecodeError:
        df = pd.read_csv(
            arquivo,
            sep=";",
            encoding="latin-1",
            nrows=5
        )
        codificacao = "latin-1"

    resultado.append({
        "arquivo": arquivo.name,
        "colunas": len(df.columns),
        "codificacao": codificacao,
        "nomes_colunas": ", ".join(df.columns)
    })

estrutura = pd.DataFrame(resultado)

display(estrutura)

,arquivo,colunas,codificacao,nomes_colunas
0,sismigra_2024.csv,17,utf-8,"DATAREGISTRO, AMPARO, AMPARO_DESCRICAO, CLASSI..."
1,sismigra_ativos.csv,8,utf-8,"unidade_da_federacao, pais, amparo, descricao_..."
2,sismigra_janeiro_agosto_2026.csv,17,utf-8,"DATAREGISTRO, AMPARO, AMPARO_DESCRICAO, CLASSI..."
3,sismigra_janeiro_dezembro_2025.csv,17,utf-8,"DATAREGISTRO, AMPARO, AMPARO_DESCRICAO, CLASSI..."
4,RAIS_CTPS_CAGED_2025_MOV.csv,21,utf-8,"competenciamov, saldomovimentacao, pais, conti..."
5,RAIS_CTPS_CAGED_2026_MOV.csv,21,utf-8,"competenciamov, saldomovimentacao, pais, conti..."
6,RAIS_CTPS_ESTOQUE_2025.csv,18,latin-1,"pais, continente, cod_uf, cod_municipio, cod_s..."
7,Tabela_Curso_Tecnico_2025_V2.csv,49,latin-1,"NU_ANO_CENSO, NO_REGIAO, CO_REGIAO, NO_UF, SG_..."
8,Tabela_Docente_2025_V2.csv,184,latin-1,"NU_ANO_CENSO, NO_REGIAO, CO_REGIAO, NO_UF, SG_..."
9,Tabela_Escola_2025_V2.csv,290,latin-1,"NU_ANO_CENSO, NO_REGIAO, CO_REGIAO, NO_UF, SG_..."
10,Tabela_Gestor_Escolar_2025_v2.csv,88,latin-1,"NU_ANO_CENSO, NO_REGIAO, CO_REGIAO, NO_UF, SG_..."
11,Tabela_Matricula_2025_V2.csv,263,latin-1,"NU_ANO_CENSO, NO_REGIAO, CO_REGIAO, NO_UF, SG_..."
12,Tabela_Turma_2025_V2.csv,218,latin-1,"NU_ANO_CENSO, NO_REGIAO, CO_REGIAO, NO_UF, SG_..."
13,MICRODADOS_CADASTRO_CURSOS_2024.CSV,223,latin-1,"NU_ANO_CENSO, NO_REGIAO, CO_REGIAO, NO_UF, SG_..."
14,MICRODADOS_ED_SUP_IES_2024.CSV,84,latin-1,"NU_ANO_CENSO, NO_REGIAO_IES, CO_REGIAO_IES, NO..."

In [46]:
# Contando os registros de cada arquivo

# Lista para guardas os resultados 
quantidades = []

# Percorrer todos os arquivos CSV encontrados
for arquivo in arquivos: 

    # Lendo o arquivo CSV
    with open(arquivo, "rb") as f:
        # Contando o número de linhas
        total = sum(1 for linha in f) - 1  # Subtrai 1 para não contar o cabeçalho

    # Guardando o resultado
    quantidades.append({
        "arquivo": arquivo.name,
        "registros": total
    })
    
# Criando um DataFrame com os resultados
contagem = pd.DataFrame(quantidades)

display(contagem)

                                arquivo  registros
0                     sismigra_2024.csv     248167
1                   sismigra_ativos.csv    3879289
2      sismigra_janeiro_agosto_2026.csv     176896
3    sismigra_janeiro_dezembro_2025.csv     265523
4          RAIS_CTPS_CAGED_2025_MOV.csv     774594
5          RAIS_CTPS_CAGED_2026_MOV.csv     550029
6            RAIS_CTPS_ESTOQUE_2025.csv     413162
7      Tabela_Curso_Tecnico_2025_V2.csv      32136
8            Tabela_Docente_2025_V2.csv     178772
9             Tabela_Escola_2025_V2.csv     214192
10    Tabela_Gestor_Escolar_2025_v2.csv     180540
11         Tabela_Matricula_2025_V2.csv     178766
12             Tabela_Turma_2025_V2.csv     178772
13  MICRODADOS_CADASTRO_CURSOS_2024.CSV     720349
14       MICRODADOS_ED_SUP_IES_2024.CSV       2561

In [48]:
# Juntar as duas tabelas pelo nome do arquivo 
inventario_final = pd.merge(contagem, estrutura, on="arquivo", how="left")

# Escolher as colunas que queremos mostrar no inventário final
inventario_final = inventario_final[["arquivo", "colunas", "registros", "codificacao"]]

display(inventario_final)

                                arquivo  colunas  registros codificacao
0                     sismigra_2024.csv       17     248167       utf-8
1                   sismigra_ativos.csv        8    3879289       utf-8
2      sismigra_janeiro_agosto_2026.csv       17     176896       utf-8
3    sismigra_janeiro_dezembro_2025.csv       17     265523       utf-8
4          RAIS_CTPS_CAGED_2025_MOV.csv       21     774594       utf-8
5          RAIS_CTPS_CAGED_2026_MOV.csv       21     550029       utf-8
6            RAIS_CTPS_ESTOQUE_2025.csv       18     413162     latin-1
7      Tabela_Curso_Tecnico_2025_V2.csv       49      32136     latin-1
8            Tabela_Docente_2025_V2.csv      184     178772     latin-1
9             Tabela_Escola_2025_V2.csv      290     214192     latin-1
10    Tabela_Gestor_Escolar_2025_v2.csv       88     180540     latin-1
11         Tabela_Matricula_2025_V2.csv      263     178766     latin-1
12             Tabela_Turma_2025_V2.csv      218     178772     latin-1
13  MICRODADOS_CADASTRO_CURSOS_2024.CSV      223     720349     latin-1
14       MICRODADOS_ED_SUP_IES_2024.CSV       84       2561     latin-1

In [49]:
# Salvando a tabela final 

# Criar a pasta reports, caso ela não exista
pasta = Path("../reports")
pasta.mkdir(exist_ok=True)

# Salvando o inventário final em CSV
inventario_final.to_csv(
    pasta / "inventario_estrutural.csv",
    index=False,
    encoding="utf-8-sig"
)

print(f"Inventário estrutural salvo em: {pasta / 'inventario_estrutural.csv'}")

Inventário estrutural salvo em: ..\reports\inventario_estrutural.csv